### ISSUE TITLE
Q: Pre-existing Polygon token, can't create interchain token

### ISSUE THREAD

**Issue by axldefi** [axelarnetwork/support#79] opened 2024-02-21 14:25 UTC
I'm trying to deploy a pre-existing Polygon token MOON (0x7AEfff599570dEC2F3DbBc2ACe3cb1F8206749eB) that was deployed initially on Polygon as an interchain token, but the interface won't allow me to do so. 

No matter what chain I select, the register button is disabled.

Tried the same process with a test token, and everything went smoothly.

![image](https://github.com/axelarnetwork/support/assets/30039844/7e90883b-3e17-45ca-b0ad-31b71c172d1c)

Appreciate any support on this matter, thank you!

**Comment by Olanetsoft** [comment] 2024-02-21 15:24
Hey @axldefi, thank you so much for bringing this to our attention. I've just gone through the process myself and encountered the same issue. Rest assured, I've already escalated this to our team internally. I'll make sure to keep you updated and provide feedback as soon as possible.

Could you please let me know which browsers and their respective versions you've used to encounter this issue? This will be incredibly helpful for our investigation. Thank you!

**Comment by axldefi** [comment] 2024-02-21 18:46
The token was created on Polygon, not as an interchain token, and was about to start the creation of the interchain process for the other chains (AVAX, Arbitrum, etc)

**Comment by canhtrinh** [comment] 2024-02-22 04:28
can you open your inspector window (option+command+i) and tell us if you see any errors in the console tab?

**Comment by axldefi** [comment] 2024-02-22 08:38
> can you open your inspector window (option+command+i) and tell us if you see any errors in the console tab?

There is no error in the Console tab, and network calls either. 

Now seems that the Register button is active, but when clicking on it the "Confirm on wallet" your wallet message is spinning, but no Metamask TX is triggered. 

Again, with 0 DEV console errors displayed.

**Comment by axldefi** [comment] 2024-02-22 12:44
> Hello @axldefi, thank you for your patience. A fix was pushed. Can you retry now?

Hello<

<img width="392" alt="image" src="https://github.com/axelarnetwork/support/assets/30039844/4a7b054e-603d-4662-bebe-c6da349d8e88">

I can click the Register button now, but unfortunately, there is no TX pop-up appearing on Metamask 

Checked both the console and network tab, and there is no error throwing.

There is an call: 
https://rpc.walletconnect.com/v1/?chainId=eip155:137&projectId=8dd25dd8f7f89b67d1c58b56f595071d

That do have the following response: 
{
    "jsonrpc": "2.0",
    "id": 8,
    "error": {
        "code": 3,
        "message": "execution reverted",
        "data": "0x2dd85afcf5ddb0c04985ee286ca7930c8dc38bcb5e71f123027cb8886b0dd834578120bd"
    }
}

It might be the reason why.

**Comment by Olanetsoft** [comment] 2024-02-22 14:18
Can you scroll down to the footer, click "Support" then click on the "Clear Cache" option and retry? @axldefi

**Comment by axldefi** [comment] 2024-02-22 14:42
Unfortunately the same scenario happening after clearing cache as well.

**Comment by canhtrinh** [comment] 2024-02-22 15:47
Ok, I can reproduce the issue of it kinda just hanging on "Confirm in Wallet" without any errors or next steps. I'll debug with the team and hope to push out a fix soon

**Comment by axldefi** [comment] 2024-02-26 06:45
Any word about @canhtrinh ?

**Comment by canhtrinh** [comment] 2024-02-26 14:16
hey @axldefi , we think the root cause is the portal erroneously recorded into our offline database the deployment of this token on polygon, even though the deployment didn't actually happen. i checked the activity for `0x4753b03e6E5b3fBaDdb938E454e8c229f1C69c1C` on Feb 7, and I don't see a deployment tx of MOON token on ITS (let me know if I'm wrong). 

So we're working on a fix to add some robustness/recovery mechanism for that scenario. If you agree that's the root cause, we'll delete the record from our offline database and have you try the registration of the MOON token on polygon again. if i'm wrong, can you share the original deployment tx of MOON token on ITS?

**Comment by axldefi** [comment] 2024-02-26 21:00
Hei @canhtrinh ! You are right, I did not finish the process, so In case you can delete the record would be best. Appreciate the support and help!

**Comment by canhtrinh** [comment] 2024-02-26 21:22
Cool, just deleted. Try again? now when you go here, you should see the option to register the token again on Polygon: https://interchain.axelar.dev/polygon/0x7AEfff599570dEC2F3DbBc2ACe3cb1F8206749eB

**Comment by axldefi** [comment] 2024-02-26 22:06
> Cool, just deleted. Try again? now when you go here, you should see the option to register the token again on Polygon: https://interchain.axelar.dev/polygon/0x7AEfff599570dEC2F3DbBc2ACe3cb1F8206749eB

Appreciate the support, it worked smoothly now! Registered on 3+ chains

**Comment by Olanetsoft** [comment] 2024-02-27 00:00
> > Cool, just deleted. Try again? now when you go here, you should see the option to register the token again on Polygon: https://interchain.axelar.dev/polygon/0x7AEfff599570dEC2F3DbBc2ACe3cb1F8206749eB
> 
> Appreciate the support, it worked smoothly now! Registered on 3+ chains

Awesome! Thank you for your patience. 🙏 I will close this now.

**Closed by Olanetsoft** 2024-02-27 00:00 UTC
Labels: bug
