### ISSUE TITLE
`deployTokenManager` stopped working?

### ISSUE THREAD

**Issue by tab00** [axelarnetwork/support#90] opened 2024-03-12 18:23 UTC
`deployTokenManager` seems to have stopped working. I tried it on some testnets but execution is always reverted.

Have there been changes made recently related to token managers that have caused this?

**Comment by benjamin852** [comment] 2024-03-12 23:55
Hey, what are you passing into the `deployTokenManager()` and on which chain are you calling this?

**Comment by tab00** [comment] 2024-03-13 04:23
> what are you passing into the deployTokenManager()

salt: 0x437573746f6d546f6b656e203100000000000000000000000000000000000000
wallet.address: 0xEB2e452fC167b5bb948c6FC2c9215ce7F4064692
tokenAddress: 0xf563e3E4186114C6887f14d4E11dcE1D6d5E1E64
TOKENMANAGERTYPE_MINT_BURN_FROM: 1

I followed the example at https://github.com/axelarnetwork/axelar-examples/blob/f2eac9a7f5aaf4d9a72b9bf86e5bbc5fb5969307/examples/evm/its-custom-token/index.js#L37-L39

> on which chain are you calling this

BNB chain testnet


Here's the error output:

```
ProviderError: execution reverted: 
    at HttpProvider.request (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\hardhat\src\internal\core\providers\http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\@nomicfoundation\hardhat-ethers\src\internal\hardhat-ethers-provider.ts:237:27)
    at C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:235:35
    at async Promise.all (index 0)
    at HardhatEthersSigner._sendUncheckedTransaction (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:125:18)
    at send (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\ethers\src.ts\contract\contract.ts:313:20)
    at Proxy.deployTokenManager (C:\Users\tab00\Documents\Projects\axelar-its-test\node_modules\ethers\src.ts\contract\contract.ts:352:16)
    at main (C:\Users\tab00\Documents\Projects\axelar-its-test\scripts\deploy-CustomTokenTokenManager.js:47:20)
```

**Comment by bilgin-kocak** [comment] 2024-03-13 15:10
I have same issues. When I run `deployTokenManager` method I get https://links.ethers.org/v5-errors-CALL_EXCEPTION call exception error. 

My paramaters were 
salt: 0x7e04743f6317f49cecfc43f1298f238c58cf505de539a9658149dafa9d9454ac
destinationChain: ""
tokenManagerType: 0
params: 0x0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000c708443711b332699c83ad32cbcb6eab9d7fb3cd000000000000000000000000000000000000000000000000000000000000001448d185bc646534597e25199dd4d73692ebd98bac000000000000000000000000

Yesterday you upgrade the Interchain Token Service contract. I think you changed something inside deployTokenManager function. In the old Interchain Token Service contract, this function works properly. If I use these parameters for below old implemtation of Interchain Token Service contract the function `deployTokenManager` works properly

https://testnet.bscscan.com/address/0x30defb998d7fddc75ffb8d002fc15bbb75115758#writeContract

**Comment by benjamin852** [comment] 2024-03-13 19:22
I see, thanks for flagging this will look internally to see what the issue is here.

**Comment by bilgin-kocak** [comment] 2024-03-15 11:55
Understanding the complexities involved in resolving such issues, I nevertheless kindly request your assistance in expediting a solution. Our client is eagerly anticipating the launch of the bridge application, and we are keen to meet their expectations within the given timeframe. If possible, could you share any updates on the resolution process, or verify the new contract in an explorer? This information could allow us to adjust our function parameters accordingly and proceed with deploying the token manager contract as planned.

**Comment by tab00** [comment] 2024-03-15 12:11
Was the new version fully tested before deployed in testnet?

It's extremely important to make sure that new versions are thoroughly tested and are fully working in your internal environment before deploying to public networks (including testnets).

**Comment by milapsheth** [comment] 2024-03-16 03:39
Hey guys, thanks for the patience and apologies for the disruption. We're making some improvements to the custom token manager flow, which required disabling token manager deployments temporarily. We're hoping to have it live soon and share more updates with you later next week.

**Comment by milapsheth** [comment] 2024-03-25 07:13
The updated version is live on testnet/mainnet. Please see release notes [here](https://github.com/axelarnetwork/interchain-token-service/releases/tag/v1.2.4) for changes to custom token deployment. Axelar docs will be updated soon as well. Let us know if you have any questions!

**Comment by Olanetsoft** [comment] 2024-03-31 22:36
@bilgin-kocak @tab00 The docs is now updated. You can refer to this guide at https://docs.axelar.dev/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens. I will now close this issue. If you have any further questions, feel free to create a new issue, and we will be happy to assist you. Thank you!

**Closed by Olanetsoft** 2024-03-31 22:36 UTC
